### ISSUE TITLE
Add more encoders/decoders - UTF-16

### ISSUE THREAD

**Issue by nadchif** [nadchif/adobe-brackets-encode-decode#19]
We need more encoders/decoders, ie String to Hex, String to MD5 etc.

To add an encoder or decoder, follow the [Contributing Guide](https://github.com/nadchif/adobe-brackets-encode-decode/blob/master/CONTRIBUTING.md)

**Comment by gauraws** [comment]
Hi, I am beginner, how can I work on this issue?

**Comment by nadchif** [comment]
@gauraws yes, please go ahead

**Comment by gauraws** [comment]
Thanks @nadchif, I will start working on this from  tomorrow onwards.

**Comment by gauraws** [comment]
Hi @nadchif I added a encoder but since my windows machine was throwing error with eslint, I executed src file separately with babel and eslint.

**Comment by nadchif** [comment]
@gauraws good work so far. I think the reason why the eslint was throwing errors is because of the CRLF / LF difference. I'm going to update a few things on Sunday or Monday, then I'll get back to you.
