### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by prakovec** [nadchif/adobe-brackets-encode-decode#20]
Hi guys!

I correctly understood that this plugin does not work with UTF-8
I use this to convert a string "мама мыла раму" and nothing happens :(

**Comment by nadchif** [comment]
@prakovec could you please provide more details and context. There's no "UTF to String" on this extension. What are you trying to achieve?

**Comment by prakovec** [comment]
@nadchif 
I need a text "мама мыла раму" string get in base64. For example:
![c6edb5c2977a603e144ab57ce40a46b1](https://user-images.githubusercontent.com/10186513/80627101-127a9500-8a58-11ea-86dc-2afb1d28deea.png)

but when i use **Encode - Decode for Brackets** the text remains the same :( 
![bb41b90bd67279d6e2791246998840a5](https://user-images.githubusercontent.com/10186513/80627328-68e7d380-8a58-11ea-94f5-7de449f52d9a.png)

when i decode  base64 **0LzQsNC80LAg0LzRi9C70LAg0YDQsNC80YM=** into a string i get **Ð¼Ð°Ð¼Ð° Ð¼ÑÐ»Ð° ÑÐ°Ð¼Ñ**  instead of **мама мыла раму**

**Comment by nadchif** [comment]
oh, I see now! Thank you for raising this issue. We will look into it. 

If you also have any ideas or thoughts on how to fix , please feel welcome to contribute

**Comment by prakovec** [comment]
Thank you so much for your help!
