### ISSUE TITLE
Add more encoders/decoders - Morse code

### ISSUE THREAD

**Issue by nadchif** [nadchif/adobe-brackets-encode-decode#24]
We need more encoders/decoders, ie String to Hex, String to MD5 etc. 

💡 Here are some ideas https://www.browserling.com/tools/

To add an encoder or decoder, follow the [Contributing Guide](https://github.com/nadchif/adobe-brackets-encode-decode/blob/master/CONTRIBUTING.md)

**Comment by okandavut** [comment]
Hi can i start with this issue?  @nadchif

**Comment by nadchif** [comment]
Yes, please go ahead ☺

**Comment by okandavut** [comment]
I added morse code converter but i will try to add more converters next days.
