### ISSUE TITLE
Add more encoders/decoders - UTF-8 

### ISSUE THREAD

**Issue by okandavut** [nadchif/adobe-brackets-encode-decode#31]

**Comment by nadchif** [comment]
@okandavut are you going to work on this one next?

**Comment by okandavut** [comment]
> @okandavut are you going to work on this one next?

Yes i want to work on this issue.

**Comment by unguest** [comment]
![image](https://user-images.githubusercontent.com/33666394/81608420-8876e880-93d6-11ea-8d6a-02aa4e485e91.png)

Hacking Brackets... Using Brackets => I think I will add some hashing-functions-oriented encoders :)

**Comment by nadchif** [comment]
@unguest thanks, please go ahead

**Comment by nadchif** [comment]
@okandavut Hi, will you still work on this? If not, I will go ahead and close this issue

**Comment by okandavut** [comment]
For these days i'm working too much in my company so i can't focus on this issue. I really want but if you want close, when i start to work  i will open new issue. @nadchif

**Comment by nadchif** [comment]
No problem, looking forward to that. Thank you for the response
