### ISSUE TITLE
Correct typos in mock.brackets.js

### ISSUE THREAD

**Issue by nadchif** [nadchif/adobe-brackets-encode-decode#41]
Good for first timers

CURRENT ISSUE: The file [/spec/support/mock.brackets.js](https://github.com/nadchif/adobe-brackets-encode-decode/blob/master/spec/support/mock.brackets.js) says "Note" on the following line:
```
3. * IMPORTANT NOTE: This is note a requireJS module.
```

WHAT WE NEED: Change "Note" to "not". It should end up something like this:
```
3. * IMPORTANT NOTE: This is not a requireJS module.
```

For a step by step guide on how to do this. See [CONTRIBUTING.md](https://github.com/nadchif/adobe-brackets-encode-decode/blob/master/CONTRIBUTING.md)

**Comment by flozender** [comment]
Hi! I'd like to help :)

**Comment by nadchif** [comment]
Thank you, proceed ☺
